# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ii98Q-GdyQYg_77I4zaVz8LSanMNN44O
"""

import pickle
import pandas
import numpy as np
import sklearn
import imblearn
import streamlit as st
from PIL import Image

st.title("Credit Card Fraud Detection Model")

st.image("Credit_Card_Fraud_Logo.jpg")



input_df = file_uploader("Upload a CSV file", type=["csv"])
df = pd.read_csv(input_df)
st.write('### Uploaded CSV file:')
st.write(df)
input_df_split = df.split(',')
submit = st.button("Submit")

if submit:
    model = pickle.load(open('model.pkl', 'rb'))
    features = np.asarray(input_df_split,dtype = np.float64)
    prediction = model.predict(features.reshape(1,-1))

  if prediction[0]== 1:
    st.write("Fradulant Transaction")
  else:
    st.write("Legitimate Transaction")